import warnings
# Suppress the xarray FrozenMapping warning if it pops up
warnings.filterwarnings("ignore", message=".*FrozenMappingWarningOnValuesAccess.*")
warnings.filterwarnings("ignore")

## gets important columns from output csv
import numpy as np
import pandas as pd
import xarray as xr
import ewstools
import statsmodels.formula.api as smf
import piecewise_regression
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.ticker import AutoMinorLocator
from statsmodels.stats.anova import anova_lm

#get this from the nc on CLIP TO BIOMES PAGE
#xarray data set and compresses it all to be a region each
ads = xr.open_dataset('/home/jovyan/workflowsREU/amazon002.nc')
print(list(ads.data_vars))

ads_mean = ads.mean(dim=("lat", "lon"))
ayr = ads_mean.to_dataframe().reset_index()

# Rename the 'time' dimension to 'yr' so it matches the rest of your script
ayr = ayr.rename(columns={"time": "yr"})
ayr.columns = ayr.columns.str.strip()

#  Choose the variables that actually exist or can be derived
vars_check = ["GPP", "NPP", "treeCA", "Indv", "mu", "LAI", "Transp", "plantC",   "fineL", "rootC", "soilC"]

# Calculate NPP dynamically (NPP = GPP - Rauto)
ayr["NPP"] = ayr["GPP"] - ayr["Rauto"]

# Keep only what you need and rename them to match your downstream code
adata = ayr[["yr", "GPP", "NPP", "treeCA", "Indv", "mu","LAI", "Transp", "plantC", "fineL", "rootC", "soilC"]].copy()
adata = adata.rename(columns={"treeCA": "Acrown", "Indv": "N_ha"})

# Update vars_check to match the renamed columns
vars_check = ["GPP", "NPP", "Acrown", "N_ha", "mu", "LAI", "Transp", "plantC", "fineL", "rootC", "soilC"]
adatatest = adata.copy()

# Collapse down by year
anewdf = adatatest.groupby("yr")[vars_check].mean().reset_index()

# Define variables for log derivatives safely
vars_check_2 = ["GPP", "NPP", "N_ha", "Acrown", "mu"]

#  log derivatives
for v in vars_check_2:
    anewdf[f"{v}_logd"] = np.log(anewdf[v]).diff()
    anewdf[f"{v}_logd"] = anewdf[f"{v}_logd"] / anewdf["yr"].diff()

logd_list = ['GPP_logd', 'NPP_logd', 'dCA_diff','dBA_diff','N_ha_logd','ht_logd','Acrown_logd','mu_logd']

#plots derivatives
anewdf['GPP_logd'].plot()

a = anewdf.copy()

## AMAZON ews loop 
aresults = []
for var in vars_check:
    # Clean out any NaNs generated by log derivatives/diffs for this specific variable
    df_clean = a[["yr", var]].dropna()
    
    
    if len(df_clean) < 3:
        print(f"Skipping Amazon {var}: only {len(df_clean)} valid data points available.")
        continue

    # make numpy arrays
    x_data = df_clean["yr"].to_numpy()
    y_data = df_clean[var].to_numpy()

    # Fit models using the cleaned numpy arrays
    m0 = smf.ols(f"{var} ~ yr", data=df_clean).fit()
    m1 = piecewise_regression.Fit(x_data, y_data, n_breakpoints=1)
    m2 = piecewise_regression.Fit(x_data, y_data, n_breakpoints=2)
    m1_res = m1.get_results()
    m2_res = m2.get_results()
    
    
    m0_bic = m0.bic
    m1_bic = m1_res.get("bic") if m1_res.get("bic") is not None else float('inf')
    m2_bic = m2_res.get("bic") if m2_res.get("bic") is not None else float('inf')
    models = [m0_bic, m1_bic, m2_bic]
    best = np.argmin(models)
    abreak = 0
    abest = 0
    delta1 = m0_bic - m1_bic
    delta2 = m0_bic - m2_bic
    
    if max(delta1, delta2) > 10:
        abest = best


    if abest == 1:
        # Get the breakpoint list if it exists, otherwise default to None
        breaks = m1_res.get("breakpoints")
        abreak = breaks[0] if breaks else 0
    elif abest == 2:
        breaks = m2_res.get("breakpoints")
        abreak = breaks[0] if breaks else 0
    else:
        abreak = 0
        
    if abreak != 0:
        ts = ewstools.TimeSeries(df_clean, transition=abreak)
        ts.detrend(method="linear")
        ts.compute_indicators(indicators=["ar1", "sd", "skew"], rolling_window=0.5)
        ts.compute_kendall_tau()

        tau = ts.ktau
        tau["var"] = var
        aresults.append(tau)

if len(aresults) > 0:
    avaluesdf = pd.concat(aresults, ignore_index=True)
else:
    avaluesdf = pd.DataFrame()

# var, can edit this for whatever variable 
acurrentvar = "GPP"
acurrentvar2 = "plantC"

plt.style.use("seaborn-v0_8-darkgrid")
fig, ax = plt.subplots(2, 2, figsize=(10, 8))
years = range(2021, 2101)
ROLL = 10

#plot var 1 
#acurentvar
a_series = pd.Series(anewdf[acurrentvar].values, index=years)
aroll = a_series.rolling(ROLL, center=True, min_periods=1).mean()
adiff = ((a_series.iloc[0]) - (aroll.iloc[-ROLL:].mean())) / a_series.iloc[0].mean()
print( acurrentvar + " differnece: " + str(adiff) )
ax[0,1].plot(years, a_series, alpha=0.3, color="green")
ax[0,1].plot(years, a_series.rolling(ROLL, center=True, min_periods=1).mean(), color="green", linewidth=2, label="Amazon")
if abreak > 0:
    ax[0,1].axvline(x=abreak, color="red", linestyle="--", label=f"Breakpoint ({int(abreak)})")
    ax[0,1].legend()
ax[0,1].set_title("Amazon " + acurrentvar + " Over Time")
ax[0,1].legend(loc="best", frameon=True)

#plot 2 
#acurrentvar2
a_series2 = pd.Series(anewdf[acurrentvar2].values, index=years)
aroll2 = a_series2.rolling(ROLL, center=True, min_periods=1).mean()
adiff2 = (a_series2.iloc[0] - aroll2.iloc[-ROLL:].mean()) / a_series2.iloc[0]
print( acurrentvar2 + " differnece: " + str(adiff2) )
ax[0,0].plot(years, a_series2, alpha=0.3, color="green")
ax[0,0].plot(years, a_series2.rolling(ROLL, center=True, min_periods=1).mean(), color="green", linewidth=2, label="Amazon")
if abreak > 0:
    ax[0,0].axvline(x=abreak, color="red", linestyle="--", label=f"Breakpoint ({int(abreak)})")
    ax[0,0].legend()
ax[0,0].set_title("Amazon " + acurrentvar2 + " Over Time")

if avaluesdf.empty:
    print("Skipping Amazon early warning indicator bar plots: No variables had valid breakpoints.")
    ax[1, 1].text(0.5, 0.5, "No Amazon Breakpoints\nDetected", 
                  ha='center', va='center', color='gray', fontsize=12)
    ax[1, 1].set_title("Amazon: Kendall's Tau (AR1)", fontweight='bold', color='gray')
else:
    acolors = ['crimson' if v == acurrentvar else 'lightgray' for v in avaluesdf["var"]]
    ax[1, 1].bar(avaluesdf["var"], avaluesdf["ar1"], color=acolors, alpha=0.7)
    ax[1, 1].axvline(0, color="black", linestyle="-", linewidth=0.5)
    ax[1, 1].set_title("Amazon: Kendall's Tau AR1")
plt.tight_layout()
plt.show() 

# Gather unique variables currently defined 
vars_indicators = list([acurrentvar, acurrentvar2])

# Process each variable dynamically
for i, test_var in enumerate(vars_indicators):
    target_df = anewdf
    modrun = "Amazon 0.2% " 
    df_source = (
        target_df.reset_index() if "yr" not in target_df.columns else target_df
    )
    df_clean = df_source[["yr", test_var]].dropna().set_index("yr")
    series_test = df_clean[test_var]
    plot_data = None
    fig = None
    if len(series_test) > 15:
        try:
            ts_test = ewstools.TimeSeries(
                series_test, transition=series_test.index[-15]
            )
            ts_test.detrend(method="Gaussian", bandwidth=0.2)
            ts_test.compute_auto(lag=1, rolling_window=0.5)
            ts_test.compute_var(rolling_window=0.5)
            plot_data = ts_test.ews.copy()
            mean_ac1 = ts_test.ews["ac1"].mean()
            print(modrun + f"Variable: {test_var:6} | Mean AC1 (lag-1): {mean_ac1:.4f}")
        except Exception as e:
            print(f"Could not process {test_var}: {e}")
            
    # TIME-SERIES PLOTTING BLOCK
    if plot_data is not None and "ac1" in plot_data.columns:
        fig, ax = plt.subplots(figsize=(7, 5))
        clean_df = plot_data.dropna(subset=["ac1"])
        calendar_years = clean_df.index.values
        relative_time = calendar_years - calendar_years[0]
        ax.plot(relative_time, clean_df["ac1"], color="#0A481E", lw=2.5, label="Lag-1 Autocorrelation")
        
        ax.set_title(f"AC1 Trajectory Over Time: {modrun.strip()} | {test_var}", fontsize=13, fontweight="bold", pad=12)
        ax.set_xlabel("Simulation Timeline (Years)", fontsize=11)
        ax.set_ylabel("AC1 Value", fontsize=11)
        ax.grid(True, linestyle="--", alpha=0.5)
        ax.set_xlim(0,35)
        tick_positions = [ 0, 10, 20, 30]
        tick_labels = [ "forty", "fifty", "sixty", "seventy"]
        ax.set_xticks(tick_positions)
        ax.set_xticklabels(tick_labels)
        ax.axhline(0, color="black", linestyle="-", alpha=0.3, lw=1)
        plt.tight_layout()
        plt.show()
        plt.close(fig) 



